{% set name = "conda-meta-mcp" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conda-incubator/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  # sha256 will be filled in when the release tag is created

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - cmm = conda_meta_mcp.cli:main

requirements:
  host:
    - python >=3.13
    - pip
    - hatchling >=1.12.2
    - hatch-vcs >=0.2.0
  run:
    - python >=3.13
    - argparse-manpage >=4.7
    - fastmcp >=2.13.1
    - conda >=26.1
    - conda-forge-metadata >=0.13.0
    - conda-package-streaming >=0.12.0
    - conda-libmamba-solver
    - pyyaml >=6.0.3
    - requests >=2.28.0

test:
  imports:
    - conda_meta_mcp
    - conda_meta_mcp.tools
  commands:
    - cmm --help

about:
  home: https://github.com/conda-incubator/conda-meta-mcp
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Model Context Protocol server providing conda ecosystem context for AI agents
  description: |
    An MCP (Model Context Protocol) server exposing authoritative, read-only Conda
    ecosystem metadata for AI agents. Provides package info, search, import mapping,
    PyPI to conda mapping, CLI help, and repository metadata queries.
  doc_url: https://github.com/conda-incubator/conda-meta-mcp#readme
  dev_url: https://github.com/conda-incubator/conda-meta-mcp

extra:
  recipe-maintainers:
    - dbast
    - jezdez
