name: Conda Meta MCP Setup
description: Set up the conda-meta-mcp for usage with GitHub Copilot coding agent.
author: conda-incubator
branding:
  icon: book-open
  color: blue

runs:
  using: composite
  steps:
    - uses: prefix-dev/setup-pixi@28eb668aafebd9dede9d97c4ba1cd9989a4d0004 # v0.9.2
      env:
        # renovate: datasource=github-releases depName=prefix-dev/pixi
        PIXI_VERSION: v0.57.0
        SETUPTOOLS_SCM_PRETEND_VERSION: 0.0.1
      with:
        manifest-path: ${{ github.action_path }}/pyproject.toml
        pixi-version: ${{ env.PIXI_VERSION }}
    - name: Make available
      shell: bash
      run: |
        mkdir -p "${HOME}/.local/bin"
        ln -s "${{ github.action_path }}/.pixi/envs/default/bin/cmm" "${HOME}/.local/bin/"
    - name: Show help
      shell: bash
      run: |
        cmm run --help
